# Generated by Django 4.0.2 on 2022-03-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrooms',
            name='isAvailable',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='meetingrooms',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
