# Generated by Django 4.0.2 on 2022-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_room_id_meetingrooms_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrooms',
            name='meeting_room',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
