# Generated by Django 4.0.2 on 2022-03-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_meetingrooms_meeting_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrooms',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
